app/jobs/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class JobForm(FlaskForm):
    title = StringField('სათაური', validators=[DataRequired()])
    description = TextAreaField('აღწერა', validators=[DataRequired()])
    salary = StringField('Salary')
    location = StringField('Location')
    benefits = TextAreaField('Benefits')
    data_verification = TextAreaField('Data Verification')
    required_skills = TextAreaField('Required Skills')
    submit = SubmitField("დამატება")

app/jobs/routes.py
from flask import render_template, request, Blueprint, redirect, url_for, flash, abort
from flask_login import current_user, login_required
from app import db
from app.models import Job
from app.jobs.forms import JobForm

jobs = Blueprint('jobs', __name__)


@jobs.route('/job/new', methods=['POST', 'GET'])
@login_required
def new_job():
    form = JobForm()
    if form.validate_on_submit():
        job = Job(title=form.title.data, description=form.description.data, salary=form.salary.data,
                  location=form.location.data, benefits=form.benefits.data,
                  data_verification=form.data_verification.data, required_skills=form.required_skills.data,
                  author=current_user)
        db.session.add(job)
        db.session.commit()
        flash('ვაკანსია წარმატებით შეიქმნა!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_job.html', title='ახალი ვაკანსია', legend='ახალი ვაკანსია', form=form)


@jobs.route('/job/<int:job_id>')
def job(job_id):
    job = Job.query.get_or_404(job_id)
    return render_template('job.html', title=job.title, job=job)


@jobs.route('/job/<int:job_id>/update', methods=['POST', 'GET'])
@login_required
def updatejob(job_id):
    job = Job.query.get_or_404(job_id)
    if job.author != current_user:
        abort(403)
    form = JobForm()
    if form.validate_on_submit():
        job.title = form.title.data
        job.description = form.description.data
        job.salary = form.salary.data
        job.location = form.location.data
        job.benefits = form.benefits.data
        job.data_verification = form.data_verification.data
        job.required_skills = form.required_skills.data
        db.session.commit()
        flash('ვაკანსია წარმატებით განახლდა!', 'success')
        return redirect(url_for('jobs.job', job_id=job.id))
    elif request.method == 'GET':
        form.title.data = job.title
        form.description.data = job.description
        form.salary.data = job.salary
        form.location.data = job.location
        form.benefits.data = job.benefits
        form.data_verification.data = job.data_verification
        form.required_skills.data = job.required_skills
    return render_template('create_job.html', title='Update Job', legend='ვაკანსიის განახლება', form=form)


@jobs.route('/job/<int:job_id>/delete', methods=['POST', 'GET'])
@login_required
def deletejob(job_id):
    job = Job.query.get_or_404(job_id)
    if job.author != current_user:
        abort(403)
    db.session.delete(job)
    db.session.commit()
    flash('ვაკანსია წარმატებით წაიშალა!', 'success')
    return redirect(url_for('main.home'))

app/main/routes.py
from flask import render_template, request, Blueprint
from app.models import Job

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    jobs = Job.query.order_by(Job.date_posted.desc()).paginate(page=page, per_page=10)
    return render_template('home.html', jobs=jobs)


@main.route('/about')
def about():
    return render_template('about.html')


@main.route('/search')
def search():
    query = request.args.get('query')
    results = Job.query.filter(Job.title.ilike(f'%{query}%')).all()
    return render_template('search.html', results=results)

app/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from flask_login import current_user, login_user, logout_user, login_required

from app import db, bcrypt
from app.models import User, Job
from app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, ResetRequestForm, ResetPasswordForm
from app.users.utils import save_picture, send_mail

users = Blueprint('users', __name__)


@users.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('მომხმარებელი შექმნილია, გაიარეთ ავტორიზაცია', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


@users.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(f'შეცდომა. გთხოვთ გადაამოწმეთ სახელი და პაროლი', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['POST', 'GET'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        # db.session.add(user)
        db.session.commit()
        flash('თქვენი პროფილი განახლებულია!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='images/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_jobs(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    jobs = Job.query.filter_by(author=user).order_by(Job.date_posted.desc()).paginate(page=page, per_page=10)
    return render_template('user_jobs.html', jobs=jobs, user=user)


@users.route('/reset_password', methods=['POST', 'GET'])
def reset_request():
    form = ResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_mail(user)
        flash('მეილი გამოგზავნილია ინსტრუქციასთან ერთად, პაროლის აღსადგენად', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['POST', 'GET'])
def reset_token(token):
    user = User.verify_reset_token(token)
    if user is None:
        flash('არასწორი ან ვადაგასული ტოკენი!', 'danger')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.add(user)
        flash('თქვენი პაროლი განახლებულია, შეგიძლიათ გაიაროთ ავტორიზაცია', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

app/templates/about.html
{% extends "base.html" %}
{% block content %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-12 offset-md-0">
            <div class="rectangle-border">
                <h2 class="white-text">ჩვენს შესახებ</h2>
                <p class="white-text lead">TechJobs-ის შესახებ: პიონერული გზა ტექნოლოგიური ბრწყინვალებისკენ</p>

                <div class="creative-content">
                    <p class="white-text">
                    TechJobs-ში ჩვენ გვჯერა, რომ ტექნოლოგია არის ინოვაციებისა და პროგრესის მამოძრავებელი ძალა. ჩვენი
                     მისიაა დავაკავშიროთ ნიჭიერი ადამიანები ყველაზე პერსპექტიულ და
                     მუდმივად განვითარებად ტექნიკურ ინდუსტრიასთან.

                    TechJobs ქმნის პლატფორმას, რომელიც არა მხოლოდ აჩვენებს უახლეს სამუშაო ადგილებს, არამედ ის არის სანდო წყარო
                        სამსახურის მაძიებლებისათვის.

                    ჩვენი პროფესიონალი გუნდი, დაუღალავად მუშაობს პლატფორმის განვითარებასა და გამრავალფეროვნებაზე პროგრამული
                        უზრუნველყოფის შემუშავებიდან ხელოვნურ ინტელექტამდე, კიბერუსაფრთხოებამდე მონაცემთა მეცნიერებამდე, ჩვენ
                        ვფარავთ დისციპლინების ფართო სპექტრს, რათა მოვუაროთ პროფესიონალებს მათი კარიერის ყველა ეტაპზე.
                    <br><br><br>
                    ის, რაც TechJobs-ს გამოარჩევს, არის ჩვენი ერთგულება სრულყოფილებისადმი და ჩვენი გაგება, როგორც სამუშაოს
                        მაძიებლების, ასევე დამსაქმებლების უნიკალური საჭიროებებიდან გამომდინარე. ვცდილობთ დავარღვიოთ
                        სტერეოტიპები და გავუმჯობესოთ სამუშაო მარკეტინგის მეთოდები,
                        რაც ხელს უწყობს სამუშაოს მაძიებლებს და დამსაქმებლებს შორის კავშირის გამყარებას.

                    TechJobs უფრო მეტია, ვიდრე უბრალოდ სამუშაო პორტალი, ეს არის კრეატიული ტექნიკური ენთუზიასტების საზოგადოება,
                        რომელიც აზიარებს ცოდნას, ხელს უწყობს თანამშრომლობას და შთააგონებს. ჩვენი ბლოგის, ღონისძიებებისა და
                        ქსელის შესაძლებლობების მეშვეობით, ჩვენ მიზნად ვისახავთ შევქმნათ ეკოსისტემა, სადაც პროფესიონალებს შეუძლიათ
                        ისწავლონ, გაიზარდონ და გრძელვადიანი წვლილი შეიტანონ ტექნოლოგიების სამყაროში.
                    <br><br><br>
                    შემოგვიერთდით ამ საინტერესო მოგზაურობაში, ჩვენ ვაყალიბებთ სამუშაო მომავალს ციფრულ ეპოქაში.
                        აღმოაჩინეთ ახალი შესაძლებლობები, გახსენით თქვენი პოტენციალი და დაიწყეთ კარიერა, რომელიც კვალს ტოვებს
                        მსოფლიოში. TechJobs აქ არის, რათა გაგიწიოთ მეგზურობა ყოველ ნაბიჯზე.

                    ერთად მოვახდინოთ რევოლუცია ჩვენს მუშაობაში და ჩამოვაყალიბოთ საუკეთესო პრაქტიკა მსოფლიოში.
                    <br><br><br>
                    კეთილი იყოს თქვენი მობრძანება Tech Jobs-ში, თქვენ აქ დაგხვდებათ ინოვაცია და პროგრესი.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/account.html
{% extends "base.html" %}
{% block content %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="rectangle-border">
                <div class="content-section">
                    <div class="media">
                        <img class="rounded-circle account-img" src="{{ image_file }}">
                        <div class="media-body">
                            <h2 class="account-heading white-text offset-md-1">{{ current_user.username }}</h2>
                            <p class="text-secondary white-text offset-md-1">{{ current_user.email }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="registration-form rectangle-border">
                    <h2 class="white-text">მომხმარებლის ინფორმაცია</h2>
                    <form method="POST" action="" enctype="multipart/form-data">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            <label class="white-text">{{ form.username.label }}</label><br>

                            {% if form.username.errors %}
                            {{ form.username(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.username(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label class="white-text">{{ form.email.label }}</label><br>
                            {% if form.email.errors %}
                            {{ form.email(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.email(class="form-control") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label class="white-text">{{ form.picture.label }}</label><br>
                            {{ form.picture(class="form-control-file") }}
                            {% if form.picture.errors %}
                                {% for error in form.email.errors %}
                                <span class="text-danger">{{ error }}</span><br>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.submit(class="btn btn-success") }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>TechJobs</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/job64.png')}}">
    <link rel="stylesheet"
          href=
                  "https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
<header class="main-header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-body-tertiary shadow-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{url_for ('main.home') }}">TechJobs</a>

            <form class="form-inline my-2 my-lg-0 ml-auto" action="{{ url_for('main.search') }}" method="GET">
                <div class="input-group">
                    <input class="form-control rounded-pill mr-sm-2" type="search" placeholder="ძიება"
                           aria-label="Search" name="query">
                    <div class="input-group-append">
                        <button class="btn btn-outline-success rounded-pill" type="submit"><i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{url_for ('main.home') }}">მთავარი</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for ('main.about') }}">ჩვენს შესახებ</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for ('jobs.new_job') }}">ახალი ვაკანსია</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for ('users.account') }}">პროფილი</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for ('users.logout') }}">გამოსვლა</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for ('users.login') }}">შესვლა</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for ('users.register') }}">რეგისტრაცია</a>
                    </li>
                    {% endif %}
<!--                    <li class="nav-item">-->
<!--                        <form class="form-inline my-2 my-lg-0" action="{{ url_for('main.search') }}" method="GET">-->
<!--                            <input class="form-control mr-sm-2" type="search" placeholder="ძიება" aria-label="Search"-->
<!--                                   name="query">-->
<!--                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">ძებნა</button>-->
<!--                        </form>-->
<!--                    </li>-->
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <div class="row">
        <div class="col">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}


            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script>
    $(function () {
        const navCollapse = $('.navbar-collapse');
        navCollapse.on('click', function () {
            navCollapse.collapse('hide');
        });
    });
</script>
<script>

    function updateClock() {
        const clockElement = document.getElementById('live-clock');
        const currentTime = new Date();
        const hours = currentTime.getHours().toString().padStart(2, '0');
        const minutes = currentTime.getMinutes().toString().padStart(2, '0');
        const seconds = currentTime.getSeconds().toString().padStart(2, '0');
        const timeString = `${hours}:${minutes}:${seconds}`;
        clockElement.textContent = timeString;
    }


    updateClock();


    setInterval(updateClock, 1000);
</script>
<script>
    $(document).ready(function () {
        const ctx = document.getElementById('sampleChart').getContext('2d');
        const myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ['დღეს', 'გუშინ', '3დღ. წინ', '4დღ. წინ', '5დღ. წინ'],
                datasets: [{
                    label: 'რაოდენობა',
                    data: [12, 19, 3, 5, 2],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    });
</script>

</body>
</html>

app/templates/forgot.html
{% extends "base.html" %}
{% block content %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="registration-form rectangle-border">
                <h2 class="white-text">Reset Password</h2>
                <form method="POST" action="">
                    {{ form.hidden_tag() }}

                    <div class="form-group">
                        <label class="white-text">{{ form.email.label }}</label><br>
                        {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.email(class="form-control") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-primary") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/job.html
{% extends "base.html" %}
{% block content %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="rectangle-border">
                <h2 class="white-text">{{ job.title }}</h2>
                <a class="mb-1" href="{{ url_for('users.user_jobs', username=job.author.username) }}"><strong>ავტორი:</strong> {{ job.author.username }}</a>
                <p class="white-text mb-1"><strong>თარიღი:</strong> {{ job.date_posted.strftime('%Y-%m-%d') }}</p>
                <p class="white-text mb-0"><strong>აღწერა:</strong> {{ job.description }}</p>

                {% if job.salary %}
                <p class="white-text mb-0"><strong>ხელფასი:</strong> {{ job.salary }}</p>
                {% endif %}
                {% if job.location %}
                <p class="white-text mb-0"><strong>მდებარეობა:</strong> {{ job.location }}</p>
                {% endif %}
                {% if job.benefits %}
                <p class="white-text mb-0"><strong>ბენეფიტები:</strong> {{ job.benefits }}</p>
                {% endif %}
                {% if job.data_verification %}
                <p class="white-text mb-0"><strong>მონაცემების გადამოწმებაზე თანხმობა:</strong> {{ job.data_verification }}</p>
                {% endif %}
                {% if job.required_skills %}
                <p class="white-text mb-0"><strong>აუცილებელი მოთხოვნები:</strong> {{ job.required_skills }}</p>
                {% endif %}
                <br>
                {% if current_user == job.author %}
                <a class="btn btn-success" href="{{ url_for('jobs.updatejob', job_id=job.id) }}">შეცვლა</a>
                <a class="btn btn-danger" href="{{ url_for('jobs.deletejob', job_id=job.id) }}">წაშლა</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block content %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="registration-form rectangle-border">
                <h2 class="white-text">ავტორიზაცია</h2>
                <form method="POST" action="">
                    {{ form.hidden_tag() }}

                    <div class="form-group">
                        <label class="white-text">{{ form.email.label }}</label><br>
                        {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.email(class="form-control") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="white-text">{{ form.password.label }}</label><br>
                        {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.password(class="form-control") }}
                        {% endif %}
                    </div>
                    <small class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label white-text") }}
                    </small>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-success") }}
                    </div>
                    <small class="form-text text-muted white-text">
                        <a href="{{ url_for('users.reset_request') }}">დაგავიწყდათ პაროლი?</a>
                    </small>
                </form>
            </div>
            <small class="login-link">
                <p class="text-center white-text">არ გაქვთ ექაუნთი? <a href="{{ url_for('users.register') }}">გაიარეთ რეგისტრაცია</a></p>
            </small>
        </div>
    </div>
</div>
{% endblock %}

app/templates/user_jobs.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-9">
            <h1 class="mb-3 white-text">{{ user.username }}-ის ყველა ვაკანსია ({{ jobs.total }})</h1>
            {% for job in jobs.items %}
            <div class="card mb-4">
                <div class="card-header text-white more-title">
                    <h5 class="mb-0">{{ job.title }}</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-2">
                            <img class="img-fluid rounded-circle"
                                 src="{{ url_for('static', filename='images/' + job.author.image_file) }}"
                                 alt="Author Image">
                        </div>
                        <div class="col-md-10">
                            <p class="mb-1"><strong>ავტორი:</strong> {{ job.author.username }}</p>
                            <p class="mb-1"><strong>თარიღი:</strong> {{ job.date_posted.strftime('%Y-%m-%d') }}</p>
                            <p class="mb-0"><strong>აღწერა:</strong> {{ job.description }}</p>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{{ url_for('jobs.job', job_id=job.id) }}" class="btn more-button">ვრცლად</a>
                </div>
            </div>
            {% endfor %}
            <div class="d-flex justify-content-center">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% for page_num in jobs.iter_pages() %}
                        {% if page_num %}
                        <li class="page-item{% if jobs.page == page_num %} active{% endif %}">
                            <a class="page-link"
                               href="{{ url_for('users.user_jobs', username=user.username, page=page_num) }}">{{
                                page_num }}</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled"><span class="page-link">...</span></li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                </nav>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card mb-3">
                <div class="card-header">
                    <div id="live-clock"></div>
                </div>
                <ul class="list-group list-group-flush">
                    {% for job in latest_jobs %}
                    <li class="list-group-item">
                        <a href="#">{{ job.title }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="card mb-3">
                <div class="card-header">
                    ვაკანსიების სტატისტიკა
                </div>
                <div class="card-body">
                    <canvas id="sampleChart" width="400" height="400"></canvas>
                </div>
            </div>

            <div class="card">
                <div class="card-header">
                    სპონსორები
                </div>
                <div class="card-body">
                    <img class="img-fluid" src="{{ url_for('static', filename='images/coke.jpg') }}">
                    <img class="img-fluid" src="{{ url_for('static', filename='images/marketer.png') }}">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}